### ISSUE TITLE
There are design discrepancies.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#31]
I tried to use Gutenberg & theme.json updates to show Gutenberg in all its glory! As a result, there were things that we couldn't do. We could patch them with some custom CSS or leave them as is. I'm not sure what to do so I opened this ticket. 

In addition, you may see some slight variations when you look at the page logged in and logged out. The editor seems to append extra classes in different ways between the 2 contexts. I designed the page to look the best when logged out. I think trying to make them look identical is probably a waste of time.

Lastly, since we are technically always viewing the block editor, we are bound to the responsivity in that context. Therefore, we have to rely on empty columns and full-width components (buttons mostly) to get the layouts to work. You'll notice this most obviously with the buttons. 

Here are some of the more visible differences:

| Design | Implementation  |
| --- | --- | 
|  ![](https://d.pr/i/sOG9e9.png)  |   ![](https://d.pr/i/sFoUYJ.png)  |
|  ![](https://d.pr/i/rApIgZ.png)   |  ![](https://d.pr/i/9PdioM.png)   |
|  ![](https://d.pr/i/2tB4Bt.png)  |   ![](https://d.pr/i/eUjMTJ.png) |
| ![](https://d.pr/i/0tp4TW.png) | ![](https://d.pr/i/CyL7gv.png) |

**Comment by beafialho** [comment]
Thanks @StevenDufresne!

- Regarding the stacked buttons in the patterns section, I think that's ok. They look good on mobile as well. The only comment I have is if it's possible to make the buttons full-width (100%)? So that we get:

| This | Instead of this |
| ----- | ----- |
| <img width="267" alt="Captura de ecrã 2022-04-28, às 10 36 45" src="https://user-images.githubusercontent.com/65220155/165724144-68a3d0ec-d0e1-4da0-b769-2b2af5bca8fc.png"> | <img width="351" alt="Captura de ecrã 2022-04-28, às 10 36 13" src="https://user-images.githubusercontent.com/65220155/165724103-178a49df-6a2c-4a40-8d99-6559923c5dec.png"> |

This was different in the mockup and you reproduced it accurately, but now looking at it, it made more sense to me this way.

- The "Gutenberg ❤️ everyone" looks ok to me too. It's fine to keep the emoji. The vertical alignment also works better than the centered one, so let's leave it.

- All the other things noted in your screenshots seem equally fine.

**Comment by StevenDufresne** [comment]
@beafialho I'll try to get the image in the right order like that in Gutenberg but we'll probably need custom CSS, the cover/image controls aren't flexible enough to play with order and absolute positioning.

**Comment by beafialho** [comment]
@StevenDufresne I was referring to the width of the buttons. I'd say it's ok if the order of the image can't be achieved though.

**Comment by StevenDufresne** [comment]
This was fixed along with #35.
