### ISSUE TITLE
Responsive text

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-gutenberg#35]
When browsing the page on mobile size, all the buttons text looks much smaller than the intended 18px. Can we match that to the mockup?

<img width="351" alt="Captura de ecrã 2022-04-28, às 10 36 13" src="https://user-images.githubusercontent.com/65220155/165725523-d80a5d59-b3c6-4394-bfbf-815a4a263677.png">

<img width="349" alt="Captura de ecrã 2022-04-28, às 10 49 21" src="https://user-images.githubusercontent.com/65220155/165726407-f620a7cb-1f70-43ef-bade-abd99541e48e.png">

Also, can we use `clamp` to make larger text smaller on mobile? This includes headings as well.

For instance, in this section the mockup uses 36px on desktop and 24px on mobile, is that the size we're using here too?

<img width="341" alt="Captura de ecrã 2022-04-28, às 10 48 22" src="https://user-images.githubusercontent.com/65220155/165726270-92809f06-947d-44a7-90d2-9f53ba2099d2.png">
<img width="327" alt="Captura de ecrã 2022-04-28, às 10 46 49" src="https://user-images.githubusercontent.com/65220155/165726278-7297b422-6fe4-4a43-a60b-2b9f0d52719b.png">

**Comment by StevenDufresne** [comment]
The block editor doesn't have a graceful way of managing responsive text (I think?). In order to get the text responsive, I've converted the font sizes to `rem` units and changed the base font size on mobile. We could use `clamp` but I'm pretty sure we'll have to do it with custom CSS. We could set defaults using `clamp`, but anyone who would update afterward would overwrite it and the document would probably fall out of sync. As I mentioned in #31, ideally we are left with a site that can be updated entirely (_almost_) in the block editor. 

I didn't do much of a font-size audit, some of it was from the original copy/paste and I'm sure some have drifted. So how about, I update the font sizes to match the designs but we stick with the `rem` unit? If we still think proportions are askew, we can move to a slightly more hard-coded theme. Thoughts?

**Comment by StevenDufresne** [comment]
Actually, after a bit more research, it looks like I can use it within the theme.json which should still make it flexible. I'll try that first :)

**Comment by StevenDufresne** [comment]
@beafialho Can you check the test site? I made some responsive text updates. Thanks :)

**Comment by beafialho** [comment]
Thanks @StevenDufresne, it's looking and working great!

I have only two comments:

- The headings are all currently set to `Light`. They should be `Regular`.
- Down at the bottom it needs some spacing above the heading:

| Currently | Mockup |
| ------- | ------- |
|  <img width="348" alt="Captura de ecrã 2022-05-03, às 10 02 50" src="https://user-images.githubusercontent.com/65220155/166428857-3cecb1c3-c7fc-447e-a5ec-ad1f290ef70d.png"> |  <img width="358" alt="Captura de ecrã 2022-05-03, às 10 05 49" src="https://user-images.githubusercontent.com/65220155/166428900-9b12316d-ccc9-4a3c-a60e-ed96c02e47ec.png"> |

**Comment by StevenDufresne** [comment]
Alright, updated. Closing this issue for now. 

In terms of future edits to padding and font sizes, etc..., I think it should be viewed as a content update... I'm not sure who managed those for .org 🤔

**Comment by beafialho** [comment]
Thanks for updating, it looks spot on now.
